"""auto add admin field

Revision ID: auto_add_admin_field
Revises: add_timezone_to_datetime
Create Date: 2026-06-16 22:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'auto_add_admin_field'
down_revision = 'add_timezone_to_datetime'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем, существует ли поле is_admin, и добавляем его если нет
    conn = op.get_bind()
    
    # Проверка существования поля
    result = conn.execute(
        sa.text("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'users' AND column_name = 'is_admin'
        """)
    ).fetchone()
    
    # Если поля нет, добавляем его
    if not result:
        op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True, server_default=sa.text('false')))
        print("✅ Добавлено поле is_admin в таблицу users")
    else:
        print("✅ Поле is_admin уже существует в таблице users")
    
    # Проверяем существование администратора и создаем его если нужно
    admin_exists = conn.execute(
        sa.text("SELECT * FROM users WHERE username = 'admin'")
    ).fetchone()
    
    if not admin_exists:
        # Хеш пароля 'admin': 7a009d60b5fd10a09eadf4044b563af1$3b6e9511dcbf5a5d5886fe746640589b43a40abbb114c27d8bfc5c4976295dda
        conn.execute(
            sa.text("""
                INSERT INTO users (username, email, password_hash, is_active, is_admin, created_at) 
                VALUES ('admin', 'admin@localhost', '7a009d60b5fd10a09eadf4044b563af1$3b6e9511dcbf5a5d5886fe746640589b43a40abbb114c27d8bfc5c4976295dda', true, true, NOW())
            """)
        )
        print("✅ Создан администратор admin/admin")
    else:
        # Обновляем существующего пользователя admin до администратора
        conn.execute(
            sa.text("UPDATE users SET is_admin = true WHERE username = 'admin'")
        )
        print("✅ Обновлен пользователь admin до администратора")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем поле is_admin (будьте осторожны - это удалит данные!)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###